[theme]
base="dark"
primaryColor="#00ff90"
backgroundColor="#101010"
secondaryBackgroundColor="#181818"
textColor="#b8ffc8"
font="sans serif"

[server]
headless = true
port = 8501

disableWatchdogWarning = true 
